sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.1
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- google-chrome --version
before_script:
- npm install
- npm run build
script:
- npm run test -- --single-run=true --browsers Chrome --code-coverage
before_deploy: "rm .gitignore"
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on: master 
after_deploy: echo 'done deploying!'