import { InputComponent } from './inputComponent';

export const INPUT_COMPONENTS: InputComponent[] = [
    { name: "surface_tension",
        tag: ["Surface Tension"],
        type: "text",
        label: 'Surface tension',
        units: 'kg/s^2',
        type_value: "float",
        min_value: "0.05",
        max_value: "0.10",
        options:["0.0725"],
        help: "A description of surface tension?"},
    { name: "viscosity_phase_1",
        tag: ["Fluid Density"],
        type: "slider",
        label: 'Viscosity (Phase 1)',
        units: 'kg/m/s',
        type_value: "float",
        min_value: "10",
        max_value: "20",
        options:["18"],
        help: "A description of surface tension?"},
    { name: "viscosity_phase_2",
        tag: ["Fluid Density"],
        type: "slider",
        label: 'Viscosity (Phase 2)',
        units: 'kg/m/s',
        type_value: "float",
        min_value: "10",
        max_value: "20",
        options:["13"],
        help: "A description of surface tension?"},
    { name: "turbulence",
        tag: ["Turbulence"],
        type: "text",
        label: 'Turbulence model',
        units: 'kg/m/s',
        type_value: "float",
        min_value: "",
        max_value: "",
        options:["False"],
        help: "A description of surface tension?"},
    { name: "pipe_radius",
        tag: ["Pipe Radius"],
        type: "slider",
        label: 'Pipe Radiusss',
        units: 'm',
        type_value: "float",
        min_value: "0.01",
        max_value: "0.10",
        options:["0.0725"],
        help: "A description of surface tension?"}
];
